project:
  name: '@project.artifactId@'
  version: '@project.version@'
  description: '@project.description@'
info:
  build:
    artifact: "@project.artifactId@"
    name: "@project.name@"
    description: '@project.description@'
    version: '@project.version@'

application:
  title: ${project.name}
  version: ${project.version}

  spring:
    output:
      ansi:
        enabled: ${SPRING_OUTPUT_ANSI_ENABLE}
    banner:
      charset: ${SPRING_BANNER_CHARSET}
      location: ${SPRING_BANNER_LOCATION}

#Logging
logging:
  level:
    org.example.resource: debug
    br.senac.go: debug
    org.springframework.web: info